# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ISBXvHbpARPnKhznQ1KbpdTpu8agxJ3P
"""

!unzip dataset1.zip -d /content/data

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras import layers, models, backend as K
import albumentations as A
import os

os.makedirs("/content/data", exist_ok=True)

trainX = np.load("/content/data/trainX.npy")
trainY = np.load("/content/data/trainY.npy")
valX = np.load("/content/data/valX.npy")
valY = np.load("/content/data/valY.npy")
testX = np.load("/content/data/testX.npy")
testY = np.load("/content/data/testY.npy")

print("Train:", trainX.shape, trainY.shape)
print("Val:", valX.shape, valY.shape)
print("Test:", testX.shape, testY.shape)


#PREPROCESS (NORMALIZE)

trainX = trainX.astype("float32") / trainX.max()
valX   = valX.astype("float32") / valX.max()
testX  = testX.astype("float32") / testX.max()
print("Normalized OK")


def show_sample(idx=0):
    fig = plt.figure(figsize=(10,5))
    plt.subplot(1,2,1)
    plt.imshow(trainX[idx][:,:,:3])  # RGB only
    plt.title("Image")

    plt.subplot(1,2,2)
    plt.imshow(trainY[idx].squeeze(), cmap='gray')
    plt.title("Mask")
    plt.show()

show_sample(5)


#DATA AUGMENTATION

aug = A.Compose([
    A.HorizontalFlip(),
    A.VerticalFlip(),
    A.RandomRotate90(),
    A.Rotate(limit=30),
    A.RandomBrightnessContrast(0.2,0.2),
    A.ShiftScaleRotate(shift_limit=0.1, scale_limit=0.1, rotate_limit=20),
    A.GaussNoise(var_limit=(0.01,0.01), p=0.5)
])

def augment_batch(images, masks):
    out_img, out_mask = [], []
    for i in range(len(images)):
        sample = aug(image=images[i], mask=masks[i])
        out_img.append(sample['image'])
        out_mask.append(sample['mask'])
    return np.array(out_img), np.array(out_mask)


def dice_loss(y_true, y_pred):
    y_true_f = K.flatten(y_true)
    y_pred_f = K.flatten(y_pred)
    intersection = K.sum(y_true_f * y_pred_f)
    return 1 - (2.*intersection + 1e-6) / (K.sum(y_true_f) + K.sum(y_pred_f) + 1e-6)

def bce_dice_loss(y_true, y_pred):
    return 0.5*K.binary_crossentropy(y_true, y_pred) + 0.5*dice_loss(y_true, y_pred)

def dice_coef(y_true, y_pred):
    y_true_f = K.flatten(y_true)
    y_pred_f = K.flatten(y_pred)
    intersection = K.sum(y_true_f * y_pred_f)
    return (2.*intersection + 1e-6)/(K.sum(y_true_f)+K.sum(y_pred_f)+1e-6)

def iou_coef(y_true, y_pred):
    y_true_f = K.flatten(y_true)
    y_pred_f = K.flatten(y_pred)
    intersection = K.sum(y_true_f * y_pred_f)
    union = K.sum(y_true_f) + K.sum(y_pred_f) - intersection
    return (intersection + 1e-6)/(union + 1e-6)


def unet_model(input_shape=(128,128,4)):
    inputs = layers.Input(input_shape)

    def conv_block(x, filters):
        x = layers.Conv2D(filters,3,padding='same',activation='relu')(x)
        x = layers.BatchNormalization()(x)
        x = layers.Conv2D(filters,3,padding='same',activation='relu')(x)
        x = layers.BatchNormalization()(x)
        return x

    c1 = conv_block(inputs,32)
    p1 = layers.MaxPooling2D()(c1)
    p1 = layers.Dropout(0.1)(p1)

    c2 = conv_block(p1,64)
    p2 = layers.MaxPooling2D()(c2)
    p2 = layers.Dropout(0.1)(p2)

    c3 = conv_block(p2,128)
    p3 = layers.MaxPooling2D()(c3)
    p3 = layers.Dropout(0.2)(p3)


    b = conv_block(p3,256)


    u1 = layers.UpSampling2D()(b)
    u1 = layers.concatenate([u1,c3])
    u1 = conv_block(u1,128)

    u2 = layers.UpSampling2D()(u1)
    u2 = layers.concatenate([u2,c2])
    u2 = conv_block(u2,64)

    u3 = layers.UpSampling2D()(u2)
    u3 = layers.concatenate([u3,c1])
    u3 = conv_block(u3,32)

    outputs = layers.Conv2D(1,1,activation='sigmoid')(u3)

    return models.Model(inputs, outputs)

model = unet_model()
model.summary()


model.compile(
    optimizer='adam',
    loss=bce_dice_loss,
    metrics=['accuracy', dice_coef, iou_coef]
)


callbacks = [
    tf.keras.callbacks.EarlyStopping(patience=10, restore_best_weights=True),
    tf.keras.callbacks.ReduceLROnPlateau(factor=0.5, patience=5)
]

history = model.fit(
    trainX, trainY,
    validation_data=(valX, valY),
    epochs=50,
    batch_size=8,
    callbacks=callbacks
)

model.save("/content/unet_model_enhanced.h5")
print("Model saved!")

plt.figure(figsize=(10,5))
plt.plot(history.history['loss'], label="Train Loss")
plt.plot(history.history['val_loss'], label="Val Loss")
plt.legend()
plt.title("Training Curve")
plt.show()

loss, acc, dice, iou = model.evaluate(testX, testY)
print("Test Loss:", loss)
print("Test Accuracy:", acc)
print("Dice Coef:", dice)
print("IoU:", iou)

def predict_and_show(idx=0, threshold=0.3):
    image = testX[idx]
    mask_true = testY[idx].squeeze()

    pred = model.predict(image.reshape(1,128,128,4))[0]
    pred_mask = (pred.squeeze() > threshold).astype(int)

    plt.figure(figsize=(12,4))

    plt.subplot(1,3,1)
    plt.imshow(image[:,:,:3])
    plt.title("Image")

    plt.subplot(1,3,2)
    plt.imshow(mask_true, cmap='gray')
    plt.title("Ground Truth")

    plt.subplot(1,3,3)
    plt.imshow(pred_mask, cmap='gray')
    plt.title("Prediction")
    plt.show()

predict_and_show(10)

from google.colab import files
import cv2
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import load_model


print("Upload a new satellite image (RGB or 4-channel):")
uploaded = files.upload()  # User selects file
filename = list(uploaded.keys())[0]


img = cv2.imread(filename, cv2.IMREAD_UNCHANGED)
if img is None:
    raise ValueError("Failed to read image. Check format and path.")


img = cv2.resize(img, (128, 128))


if img.shape[2] == 3:
    nir = np.zeros((128,128,1), dtype=img.dtype)
    img = np.concatenate([img, nir], axis=2)


img_input = img.astype("float32") / img.max()
img_input = img_input.reshape(1,128,128,4)


model = load_model("/content/unet_model_enhanced.h5", compile=False)
model.compile(optimizer='adam', loss='binary_crossentropy')


pred = model.predict(img_input)[0]
pred_mask = (pred.squeeze() > 0.3).astype(np.uint8)  # threshold 0.3


plt.figure(figsize=(12,4))

plt.subplot(1,3,1)
plt.imshow(img[:,:,:3])
plt.title("Input Image")

plt.subplot(1,3,2)
plt.imshow(pred_mask, cmap='gray')
plt.title("Predicted Mask")


overlay = img[:,:,:3].copy()
overlay[pred_mask==1] = [255,0,0]  # Red overlay
plt.subplot(1,3,3)
plt.imshow(overlay)
plt.title("Overlay")
plt.show()


cv2.imwrite("predicted_mask.png", pred_mask*255)
print("Prediction saved as predicted_mask.png")